version: '3'

services:
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_PORT=9092
  influxdb:
    image: influxdb:1.2.4-alpine
    ports:
      - 8083:8083
      - 8086:8086
      - 2003:2003
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  grafana:
    image: grafana/grafana:4.3.2
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1ccl@b2017
